name: Build sourcepawn and commit

on:
  workflow_dispatch:
  push:
    paths:
      - '**.sp'
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Compile sourcepawn
        uses: spiretf/spcomp@v0.1.0
        with:
          source: './executeonjoin.sp'
          target: './executeonjoin.smx'
    
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add executeonjoin.smx
          git commit -m "Compile sourcepawn" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}