name: Compile with SourceMod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    name: SM version ${{ matrix.sm-version }}
    steps:
      - uses: actions/checkout@v1
    
      - name: Setup SP
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: '1.10.x'
          version-file: ./executeonjoin.sp
    
      - run: |
          spcomp executeonjoin.sp -o output/executeonjoin.smx
          echo Plugin version ${{ steps.setup_sp.outputs.plugin-version }}